### ISSUE TITLE
The cursor is hard to grasp with Oculus Touch.

### ISSUE THREAD

**Issue by umiyuki** [umiyuki/Artstage-Issues#1]
Posted from the steam thread board.
https://steamcommunity.com/app/523050/discussions/0/1680315447979336092/

That said, I would like to point out that for whatever reason its very hard to grab the cursor to rotate it with the oculus touch controllers. Sometimes it takes me a full minute before I am able to grab onto it.

**Comment by Ekrons** [comment]
I can't grab it at all. I move controller to it, the cursor is highlighted, but nothing happens to the mesh when I interact with the cursor.

**Comment by umiyuki** [comment]
I think that this problem is caused by the fact that the point to be grasped by Oculus Touch is hard to understand.

Can't you grab it while the cursor is highlighted?
You need to drag while holding the trigger of the left hand controller to grab the cursor of the right hand controller.
If you still can not grasp it, some kind of bug has occurred.

**Comment by Ekrons** [comment]
Everything works well. Maybe when I last used the cursor on the object nothing was selected.
The cursor quickly reacts with the Oculus Touch. I do not know what the problem is this topic.

**Comment by Aitolda** [comment]
The problem is that most of the time the cursor won't highlight as i move my touch controller up to it,  or it highlights for a tiny fraction of of a second before I can grab it.

**Comment by Aitolda** [comment]
Your update completely solved the issue!

**Comment by umiyuki** [comment]
This issue is closed with the update of Ver 0.8.0.
Thanks.
