### ISSUE TITLE
Cancel the last cut with the knife tool.

### ISSUE THREAD

**Issue by umiyuki** [umiyuki/Artstage-Issues#10]
Posted from steam thread board.
https://steamcommunity.com/app/523050/discussions/0/1770385542779403272/

In the process of creating cuts with a knife, we cannot cancel every last cut.

**Comment by Ekrons** [comment]
This issue can be closed. Thanks)

**Comment by umiyuki** [comment]
This request is implemented in Ver0.8.1.
Thanks.
