### ISSUE TITLE
Rename layers.

### ISSUE THREAD

**Issue by umiyuki** [umiyuki/Artstage-Issues#11]
Posted from steam thread board.
https://steamcommunity.com/app/523050/discussions/0/1770385542779403272/

**Comment by Aitolda** [comment]
I don't see the option to upvote this one, but I agree.

**Comment by Ekrons** [comment]
I thought about it and realized that hardly anyone would want to rename a bunch of layers. With the virtual keyboard it is inconvenient to do this.
It would be better if the layers could be arranged in groups. For example, the group "man", the group "house", the group "spaceship", etc. What will unload and order the layers panel.

**Comment by Ekrons** [comment]
Thanks for the feature! This issue may be closed.

**Comment by umiyuki** [comment]
This function was implemented in Ver0.8.4.
Close this issue.
