### ISSUE TITLE
Increasing and decreasing the sphere of influence works poorly on the Oculus.

### ISSUE THREAD

**Issue by umiyuki** [umiyuki/Artstage-Issues#13]
Posted from trello.
Increasing and decreasing the sphere of influence works poorly on the Oculus.
Sometimes I accidentally increase it a lot, and then I cannot reduce it, since there is no specific button for that. Stick does it, but badly.
For the increase and decrease should be responsible stiсk, but correctly.

**Comment by Ekrons** [comment]
Here is the video of demonstration this bugs.
https://youtu.be/k2kH7l6_M10

It is also impossible to scale an object by holding trigger and tilting the stick. This is shown in the video.
There is no clear resizing, the size changes unpredictably.

**Comment by Aitolda** [comment]
I have the exact same issue while painting as well. Trying to change the size of my paintbrush is difficult and time consuming, due to the same root problem.  My assumption was that artstage was designed with vive wands in mind rather than the rift thumbsticks.

**Comment by Ekrons** [comment]
Thanks for the Touch support. Now this issue can be closed.

**Comment by Aitolda** [comment]
This is now working perfectly. Thanks for the hard work!

**Comment by umiyuki** [comment]
This issue is closed with the update of Ver 0.8.0.
Thanks.
