### ISSUE TITLE
Mirror Mesh

### ISSUE THREAD

**Issue by Ekrons** [umiyuki/Artstage-Issues#18]
This is not the usual mirroring when we modeling one side and automatically create a mirror side.
Mirroring, which I ask for, is used when the finished object is looking to the left, and we need to mirror it to the right.
![14 Ctrl+M shortcut (Mirroring)](https://user-images.githubusercontent.com/50044554/56849002-89d29180-68f7-11e9-8dd8-0ec25ef33543.gif)

**Comment by umiyuki** [comment]
Mesh mirroring is possible now with the scaling action implemented in Ver0.9.0. Close this issue.
