### ISSUE TITLE
eyedropper should not copy alpha values

### ISSUE THREAD

**Issue by umiyuki** [umiyuki/Artstage-Issues#2]
Posted from the steam thread board or trello.
https://steamcommunity.com/app/523050/discussions/0/1770385542779403272/

-----
Bug: When I take color with eyedropper, alpha channel resets to 255. It is necessary that transparency is not copied with color data.

-----
On the contrary, it copies the alpha channel, but it should not.
I paint with a translucent brush, then with a eyedropper I take some color, and the transparency of the brush gets lost, it becomes opaque. And so every time.

**Comment by Ekrons** [comment]
I made a video showing this problem.
https://www.youtube.com/watch?v=aF202gYzk_o

**Comment by umiyuki** [comment]
In the current version, you can now choose whether to get the alpha value when eyedropper. Close this issue.
