### ISSUE TITLE
When OBJ is imported, it's not split into separate layers by linked meshes.

### ISSUE THREAD

**Issue by Ekrons** [umiyuki/Artstage-Issues#21]
https://youtu.be/PG-bFws1btw
In the first part of the video, you can see that the mesh is not splitted into separate layers.
In the second part, you can see that the mesh is wrong splitted. Perhaps so conceived..

In any case, there is no option when the OBJ is splitted into layers by linked meshes.

You might say that the mesh is too dense. I loaded the same object in low poly, and it also didn't separated into layers by linked meshes.

Here is meshes used in video.
https://drive.google.com/open?id=1dLFzQXmysuuWaUZa1DRV-uHNOIuPqe-n

**Comment by Ekrons** [comment]
Here is meshes used in video.
https://drive.google.com/open?id=1dLFzQXmysuuWaUZa1DRV-uHNOIuPqe-n

**Comment by umiyuki** [comment]
Your obj file has only one mesh group.
Obj files are divided into groups when loading. I tried to read this obj file in Blender, also it was read as a single object.

You need to obj export the objects you want to split as separate groups.

**Comment by Ekrons** [comment]
umiyuki
Thanks, now separated)

**Comment by umiyuki** [comment]
It was good to solve it.
I'll close this issue.
