### ISSUE TITLE
Delete vertice and edge

### ISSUE THREAD

**Issue by Ekrons** [umiyuki/Artstage-Issues#26]
umiyuki wrote: "Delete edges and delete points works like this in Maya.
When you delete an edge in Blender, it actually removes the face that contains the edge, not the edge."

In Blender it happens absolutely logically.
I will conduct an anology with a fishing net.
Delete. If we cut off one of the knots of the fishing net, this section will disintegrate. That's what it should be called "delete".
Dissolving. If we untie the knot, the knot will disappear, but the integrity of the fishing net will not be broken.

Both functions are very useful.
Sometimes it's convenient to not switch to the selection of faces. Just select the vertex, and remove it along with the adjacent edges.

For example, you will need to DELETE edge loop. Are you going to highlight all these adjacent faces? No, it is easier to select a loop and delete it, but the faces will be deleted along with it.

**Comment by Ekrons** [comment]
I realized that your delete tool has everything we need. There is no need to add anything, let everything remain as it is. Thank you.
Issue can be closed.

**Comment by umiyuki** [comment]
Close this issue.
Thanks.
