### ISSUE TITLE
Previous model's texture carries over when starting a new model

### ISSUE THREAD

**Issue by Aitolda** [umiyuki/Artstage-Issues#27]
When starting a new model, the previous models texture set isn't cleared

1. Open a model
2. Use texture paint
3. Open a new model
4. Old texture will appear on the new model.

**Expected behavior**
A new model should start with a fresh white texture.

**Desktop (please complete the following information):**
 - Artstage Version 0.8.0

**Comment by umiyuki** [comment]
This issue is fixed in Ver0.8.1.
Thanks.
