### ISSUE TITLE
Edge loop select not functioning on Oculus Rift

### ISSUE THREAD

**Issue by Aitolda** [umiyuki/Artstage-Issues#31]
**Describe the bug**
attempting to select an edge loop on oculus Rift by double tapping the A button does not select edge loop.

**To Reproduce**
1. Using an Oculus Touch controller select edge mode
2. hover the sphere of influence over an edge that's part of a loop.
3. Double tap the A button

**Expected behavior**
Per version 0.7.6 double tapping select on an edge should select an edge loop.

 - Artstage Version [e.g. 0.7.6]

**Comment by Ekrons** [comment]
This issue can be closed.

**Comment by umiyuki** [comment]
This issue is fixed in Ver0.8.1.
Thanks.
