### ISSUE TITLE
Shape tool must have presets for each shape.

### ISSUE THREAD

**Issue by Ekrons** [umiyuki/Artstage-Issues#33]
Now, many forms have zeros in the settings, which is why the form is not visible on the scene during quick creation.
Now the optimal pre-settings have only a sphere and a plane.
Maybe I'm wrong in something?

**Comment by umiyuki** [comment]
In previous versions, there may be a bug that the settings is reset to zero. This problem should be fixed in the current version.
You should be able to fix it once you reset the settings from Preference. If the same problem occurs again, the bug will not have been fixed.

**Comment by umiyuki** [comment]
Since there is no reply, it is considered that it has been solved, and it closes once. If you are still having problems, please reopen.
