### ISSUE TITLE
Duplicate Mirror or Flip Normals tool bug

### ISSUE THREAD

**Issue by Ekrons** [umiyuki/Artstage-Issues#35]
1. Use "Duplicate mirror" function with mesh.
2. Select "extrude tool" (edge).
3. Extrude the edge of this mirrored mesh, and notice that the extruded edge creates a face with inverted normal. Well, let's try to flip normal with "flip normals tool". This happens successfully. 
But what if we extrude edge from this face again? Again face with inverted normal.

If we check the "flip normals tool" on a regular mesh, we see that it doesn’t work so well by default.
It would be more logical if from inverted face were extruded inverted face.

That is, you need to solve the problem in some of these ways:
- From inverted face must be extruded face with the same normal direction.
or
- "Duplicate Mirror" mesh should not create inverted polygons during extrusion.

**Comment by umiyuki** [comment]
This bug has been fixed in the latest version. Close this issue.
