### ISSUE TITLE
Letter "S" on a layer panel, what means "solo". Hided other layers ecsept current.

### ISSUE THREAD

**Issue by Ekrons** [umiyuki/Artstage-Issues#39]
So that other objects do not interfere with editing the current one.

**Comment by MarkMironov** [comment]
Also a good feature that is always present in other programs. Without it, you have to turn off the eye icon on each layer, except for the necessary one.

**Comment by umiyuki** [comment]
The method to show and hide all objects at once was implemented in ver0.9.1. Close this issue.
