### ISSUE TITLE
Make the back face translucent.

### ISSUE THREAD

**Issue by umiyuki** [umiyuki/Artstage-Issues#4]
Posted from steam thread board.
https://steamcommunity.com/app/523050/discussions/0/1770385542779403272/

Also, transparent backfaces are misleading.
In ZBrush and Blender, it is possible to display slightly shaded opaque backface, which simplifies the understanding of geometry.

**Comment by Aitolda** [comment]
I certainly wouldn't mind at least some indicator when looking at a backface.  I'm not sure it has to be absolutely transparent as you said, so perhaps partial oppacity might work.  Either way some version of this might be helpful.

**Comment by umiyuki** [comment]
>Ekrons
I'd like to investigate the behavior of the showing back faces in blender. Please tell me how I can set it in blender.

**Comment by Ekrons** [comment]
@umiyuki Here's how it looks in Blender 2.7.
![GIF3](https://user-images.githubusercontent.com/50044554/62858181-4d8a3c00-bd02-11e9-8b6b-3933e98a5e2b.gif)

**Comment by umiyuki** [comment]
@Ekrons
Thanks. It looks like the back faces is displayed the same as the front faces. I think it's more confusing than the back faces doesn't appear.

**Comment by Ekrons** [comment]
@umiyuki
Yes, but the back faces have a different color, darker.
Fully transparent backfaces mislead that there is no face at all.

**Comment by Ekrons** [comment]
@umiyuki It is still inconvenient that the backfaces are transparent. 
For example, if the plane is turned away from us, then you can’t find it.
Sometimes I have to rotate the scene to make sure that there are no turned objects anywhere.

The edges are too transparent if they were at least a bit opaque.

**Comment by MarkMironov** [comment]
Since transparency is often useful, I suggest that you do not make the edges too opaque. 5-10 percent would be enough.

**Comment by MarkMironov** [comment]
@umiyuki Thank you for the opportunity to change the color of the back faces! It would be nice if we could change the color of the front edges in the same way.

**Comment by umiyuki** [comment]
Back faces display was implemented in ver0.9.1. Close this issue.
