### ISSUE TITLE
Floor Boundaries Off

### ISSUE THREAD

**Issue by parsec3d** [umiyuki/Artstage-Issues#50]
This might not be related to Artstage.. but if so an option to turn off floor boundaries

![snaps](https://user-images.githubusercontent.com/40684871/63825734-7e34bd00-c921-11e9-92f9-e6e80ff69c31.jpg)

**Comment by Ekrons** [comment]
@umiyuki  Thanks for the feature! This issue may be closed.

**Comment by parsec3d** [comment]
Awesome ! . Thanks!
