### ISSUE TITLE
Rift S controller ring pops out of the menu.

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#55]
![Image 2019, 09, 15, 12, 25, 58](https://user-images.githubusercontent.com/55280047/64919976-911d0d80-d7ba-11e9-9821-a17642ffef31.png)

**Comment by umiyuki** [comment]
Until now, even though Rift S was used, the previous Oculus Touch model was displayed, but it seems that a new Touch has been displayed by updating SteamVR.

The new Touch ring is a hindrance to the UI display. Future versions may be forced to replace the previous Touch model for display.
Even in the current version, you should be able to manually return the controller model to the previous Touch. Try selecting Touch as the controller type in Preferences.

**Comment by MarkMironov** [comment]
That helped. Thank you.

**Comment by umiyuki** [comment]
With the update of 0.8.4, even if you use Rift S and set the controller type as default, you should be able to see the old Touch, but I don't have Rift S. The operation has not been confirmed.
Would you please check if it actually works like that?

**Comment by MarkMironov** [comment]
@umiyuki When "default" is selected, CV1 controllers are displayed. When "oculus touch" is selected, then Rift S controllers.
But several times I saw that on the left was CV1 controller, and on the right was Rift S. I did not understand why this was happened.
Also, it was that I selected "default", but on the next launches the "oculus touch" profile was displayed. Even now, I launched Artstage and saw the Rift S controllers, despite the fact that before that I set the CV1.

**Comment by MarkMironov** [comment]
@umiyuki I just tried again and saw that both "oculus touch" and "default" profiles  displayed CV1 controllers on both hands.

**Comment by umiyuki** [comment]
It seems to work mostly, but seems to have some problems. In any case, further improvement is difficult until I got Rift S.
Thanks for testing!
In the future, new VR controllers such as Knuckles and Vive Cosmos will appear one after another, but it is difficult to check everything.

**Comment by MarkMironov** [comment]
@umiyuki ок, thanks!
