### ISSUE TITLE
More convenient file saving.

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#57]
As you know, the model often has to be saved so as not to lose the result in case of a program error. Now the save button is located inconveniently, and every time the file browser opens. Please add the "SAVE" button to a more convenient place, and let the "SAVE AS" button be in the same place.

**Comment by umiyuki** [comment]
![savebutton](https://user-images.githubusercontent.com/6958622/65366495-b9e04f80-dc5f-11e9-9618-5e46b4a1553e.jpg)
The save button is here.
This is a convenient location.
When this button is pressed, the file browser is displayed only for the first time, but it is automatically overwritten after the second time.
Only if you want to rename, press the modeling menu → "Save model" button.
You say that you also want the "Save as" button in a convenient position. For example, after pressing this save button, a dialog will appear that allows you to select options such as "Overwrite", "Save as(Show file browser)", "Auto Rename(Add number to last filename)" How about it?

**Comment by MarkMironov** [comment]
@umiyuki I did not notice this button. In this case, everything suits me. Sorry)

**Comment by umiyuki** [comment]
Do not worry.
Close this issue.
