### ISSUE TITLE
What are the texture layers in Artstage?

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#58]
I loaded an unwraped plane into the scene. Loaded and applied texture (image) to this plane. Then I created a sphere on new layer, and found that the sphere has the same texture as the plane. Whatever object I create, this image is displayed on all.
I created a new texture layer, but that did not help.

Is it possible to somehow bind a texture layer to layers of objects? For example, we create a layer of objects, and indicate which layer of textures will affect on it.

Now texture layers work in an incomprehensible way. Or I just didn’t figure it out.
Sorry for my english.

**Comment by umiyuki** [comment]
Artstage only handles one texture per model.
Texture layers does not mean multiple textures. That means layers of single texture.
The texture layer means same as the layer of Photoshop.

If you want to paint a sphere with a different color than the plain texture, do "Unwrap & Bake" once.
The plain and sphere UVs are unwrapped and the texture is baked.
Subsequent painting on the sphere will not affect the texture on the plane.

**Comment by MarkMironov** [comment]
@umiyuki 
1. After baking, new objects are created not white, but with a whole common texture. Is it possible to allocate white space on the texture for new objects? Or make a button that allows you to fill with white the area of the texture belonging to the selected mesh.

2. When I turn on subdiv, all the polygons on the object with texture become transparent.

3. If you hide the layer with the object, then click "bake", after this the hidden object will lose his texture and become transparent.

4. If we select the "texture paint tool" and click "bake", we will draw a point on the texture if we directed the controller at the moment of clicking on the texture.

**Comment by umiyuki** [comment]
These three problems have been fixed in Ver0.8.5.
