### ISSUE TITLE
3 features: "duplicate mesh in the layer",  "select linked mesh in the layer" and "mirror selected mesh in the layer"

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#64]
When there are many layers, it is inconvenient to switch between them. But when all meshes is in one layer, in order to duplicate one element, you have to duplicate the entire layer.
Please create mesh duplication functions. They could be on the "Action" tab or somewhere else.

"Select linked mesh in the layer" also important because individual meshes often intersect, and it is difficult to select one of them to move.

Or make a more convenient layer panel where you can add layers to expandable layer groups. And so that at least 15-20 elements (groups or layers) can be placed in the visible area of the layer window.

**Comment by umiyuki** [comment]
Linked mesh selection was implemented in Ver0.8.5. The other two are not yet.

**Comment by MarkMironov** [comment]
@umiyuki Thank you. At least the duplication function is still needed ...
Better, of course, with mirroring.

**Comment by MarkMironov** [comment]
umiyuki, awesome! Thank you!
