### ISSUE TITLE
On the axis of symmetry, the vertices must be merged. Otherwise, it is difficult to place the vertices so that there is no gap.

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#69]
And the subsurf looks ugly on the axis.

**Comment by umiyuki** [comment]
The mirror display gap can be filled by aligning the X coordinate of the selected vertex with 0 using the MoveTo command.
The setting of MoveTo command is Absolute, individual, x axis only, x = 0.

> And the subsurf looks ugly on the axis.
While I wasn't aware of such problems while using Artstage, there might be something special probrem. I need more detailed explanation.

**Comment by MarkMironov** [comment]
@umiyuki thank you! "Pin vertives with "X" position zero" helped in couple with "Move to". 
Now the subsurf looks good on the line of symmetry)

**Comment by umiyuki** [comment]
When the MoveTo action is executed using a shortcut, the previous settings are applied, so it is convenient to use the shortcut for the second and subsequent executions.
I use this a lot.
