### ISSUE TITLE
If we paint the model, and then click "bake", dark stripes will appear on the texture at the seams.

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#70]
https://youtu.be/M_7hHKfBoBA

If you paint over these lines and press "bake" again, they will appear again.

![Image 2019, 10, 20, 15, 33, 31](https://user-images.githubusercontent.com/55280047/67159605-57a66780-f34f-11e9-924f-87c2d68ff199.png)

**Comment by umiyuki** [comment]
Unfortunately, this is a bug that was occured when other problems were fixed in Ver0.8.4.
I noticed this issue the other day and it has now been fixed locally.
That will be fixed in the next update.
