### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#71]
https://youtu.be/vjeLcBEXqAI

I created a model, clicked "bake", and got a UV in which there was such a repeating section.
https://youtu.be/6A8hjw-RWfk

**Comment by umiyuki** [comment]
Artstage's automatic UV unwrapping is not yet perfect, and there is a rare problem that UVs overlap on multiple faces.
I have been working on improving UV unwrapping, but for the time being, it should be possible to avoid duplication by dividing the faces where UVs overlap into separate objects.
Alternatively, you can export to an obj file, and unwrapping UV with software such as Blender.

Sending an asm file that reproduces the problem will help to improve the problem.
https://www.dropbox.com/request/HOU04JVUNXAlPxqmOMUu

**Comment by MarkMironov** [comment]
@umiyuki 
I sent a file with a repeating section of texture to Dropbox. (Called "Texture repeated area")
There is another bug in the same file.
The vertex shifts when the edge is removed.
https://youtu.be/Cd1VYJq-9S8

**Comment by umiyuki** [comment]
Thank you for sending your file!

>The vertex shifts when the edge is removed.

This is probably not a bug. If deleting vertices and edges results in illegal geometry, they are all removed. Because illegal geometry can cause critical problems for subsequent mesh edit.
You have to clean  geometry before deleting the edges.

**Comment by MarkMironov** [comment]
@umiyuki But can you fix the bug with triangular faces? I think you understand that a mesh does not always consist of quadrangles, sometimes triangles are needed. But in this case, the program often freezes.

**Comment by umiyuki** [comment]
Sorry about the triangle bug. My test on Subdiv was inadequate and caused a careless bug.
I hurriedly fixed this critical bug. It will be reflected in the next update.

**Comment by MarkMironov** [comment]
@umiyuki thank you)
