### ISSUE TITLE
When the vertices are splitted, the subsurf is not displayed correctly.

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#75]
https://youtu.be/hEE0FQ6iYaM
File sent to Dropbox. Called "splitted vertices subsurf bug".

**Comment by umiyuki** [comment]
Thank you for sending the file!
I didn't realize this problem, but it can happen. OpenSubdiv can't distinguish multiple vertices at the same positions, and merges them. And Move tool does not update the Subdiv geometry for optimization. They cause this problem.
I was troubled, but decided to cope by shifting the positions of the splitted vertices slightly.
Anyway, the local fix is ​​complete and will be reflected in the next update.

**Comment by MarkMironov** [comment]
@umiyuki thank you very much!
