### ISSUE TITLE
Subsurf seams. It feels like UV is affecting the subsurf.

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#79]
https://youtu.be/7nU2X_AE5IY
1. First, I checked the whole model for double vertices.
2. Then bake the texture.
3. Paint the mesh.
4. Found several seams on the model.
5. Again collapse vertices at the seams.
6. Bake the texture.
7. Painted the model in the place where there was a seams.
8. Again I found a seam in the same place!

These seams spoil the look of the model. It should be completely smoothed.

File sent to Dropbox. Called "Subsurf seams".

-------------------------

Another case:
https://youtu.be/ZMN74kiuQrM
If we apply subsurf to the cube that loads when the program starts, we will see that it is not completely subdivided. Where the edges were, seams are visible.  Could it be UV seams? In any case, should they be visible when subdiv applied? I didn’t assign any weights to the edges, which means the mesh should be completely smoothed.
And why do the seams disappear with the collapse of the vertices? Are there double vertices there? No. But why does vertex collapse improve the appearance of the object?
![Image 2019, 10, 23, 12, 24, 44](https://user-images.githubusercontent.com/55280047/67378787-75aeda80-f590-11e9-9c77-8307bba82df6.png)

**Comment by umiyuki** [comment]
As you say, it seems that Subsurf seams occur along UV seams. However, there is actually no gap. If there is a gap, there will be a hole.
This is a temporary appearance problem and will eventually disappear if you freeze Subsurf. I didn't pay much attention.
However, because you are worried, I fixed it. This will be reflected in the next update.

**Comment by MarkMironov** [comment]
@umiyuki Great news. Thank you!
Freezing subdivs means increasing the number of polygons and making the mesh more difficult to edit.

Could you add this fix to the current version? (what came out recently)
I would like to test it, and check if the vertices were splitted because of it, or there was some other reason. This check may take a long time.

**Comment by umiyuki** [comment]
Unless it is a fatal bug, the application is not updated every time a bug is fixed. Release work takes time and slows down the development progress of the application.

**Comment by MarkMironov** [comment]
@umiyuki, finally! thank you!)
