### ISSUE TITLE
When I import an OBJ file, it is triangulated. Also we need scale adjustor when import.

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#84]
This despite the fact that I exported the model in quads.
We need a tick that will turn off triangulation.
It would also be a good opportunity to choose the scale when import. Because often OBJ files on a computer at different scales. And resizing them after import is less convenient.

**Comment by MarkMironov** [comment]
@umiyuki , Models are still triangulating :(

**Comment by umiyuki** [comment]
Do you not allow application updates until I solve all issues?

**Comment by MarkMironov** [comment]
@umiyuki Sorry.

**Comment by MarkMironov** [comment]
@umiyuki Thanks for quads!

**Comment by umiyuki** [comment]
Improvement to keep quad when obj open was implemented in ver0.9.1. Close this issue.
