### ISSUE TITLE
When using an image sketch, some interface elements become invisible if there is an image behind them.

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#85]
https://youtu.be/IWjsVnPwso4

The sphere of influence and the edges lose their visibility. Maybe vertices too, I did not check.

**Comment by umiyuki** [comment]
I don't have the problem locally now, so it may have been discovered and fixed after the release of Ver0.8.5. It will be reflected in the next update.

**Comment by MarkMironov** [comment]
@umiyuki thanks!

**Comment by MarkMironov** [comment]
@umiyuki Edges still invisible.
