### ISSUE TITLE
When extruding, the extrudable part is not visible. Only after releasing the trigger it appear.

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#86]
When you don’t see what you are moving in your hand, this creates inconvenience in modeling.

**Comment by umiyuki** [comment]
The problem is unclear. The extrusion part is previewed during extruding.

**Comment by MarkMironov** [comment]
@umiyuki Yesterday I extruded and the extrudable part did not display at all. It turned out to be a rare bug that did not happen again.
Unfortunately, I thought that extruding in Artstage works like that, so I did not save the file with the bug.
If the issue gets in the way, you can close it. If I find this bug again, I’ll create a new one.

**Comment by umiyuki** [comment]
Close this issue.
