### ISSUE TITLE
The ability to select vertices in an extrusion tool and extrude them as not vertices, but edges.

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#91]
Imagine we need to extrude a pipe to make it longer.
With the current selection of edges, we will not be able to select the entire border edgeloop with one click of the trigger. Otherwise, longitudinal ribs will be also selected.

I propose making it possible to select vertices and then extrude them like edges. So we can select the entire border edgeloop with one click of the trigger.

Now, to select the border edgeloop, you need to select each border edge. It is too long.

**Comment by umiyuki** [comment]
1. Select the edge you want to extrude
2. Deselect the extra selected edges.
With two clicks you can select the required edge. This is enough.
If implemented the requested feature, requires extra effort, such as selecting a vertex after enabling the feature.

**Comment by MarkMironov** [comment]
@umiyuki 
Thats true. Close issue.
