### ISSUE TITLE
How can I remove a selected loop and his vertices?

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#93]
Without hole formation. So that the loop disappears, and the faces merge.

I was not even able to delete it by deleting each individual vertex.

![Image 2020, 01, 22, 16, 15, 07](https://user-images.githubusercontent.com/55280047/72902213-bf47c680-3d33-11ea-8479-d47d286b020d.png)

**Comment by MarkMironov** [comment]
I have found a way. First, I delete each edge individually, and then each remaining vertex. A long way ...

**Comment by umiyuki** [comment]
1. Select edge loop
2. Delete elements action
3. Delete vertices with delete tool

**Comment by MarkMironov** [comment]
@umiyuki Thanks. I am closing this thread. But if you have the opportunity, please simplify this action in the program.
